name: 'Reusable composite action for Trivy vulnerability scanning'
inputs:
  tag:
    required: true
  module:
    type: string      
  acr:
    type: string
  registry_username:
    type: string
  registry_password:
    type: string
  token:
    type: string


runs:
    using: "composite"
    steps:

      - name: 'Checkout GitHub Action'
        uses: actions/checkout@main

      - name: 'login to ACR'
        uses: azure/docker-login@v1
        with:
          login-server: ${{ inputs.acr }}
          username: ${{ inputs.registry_username }}
          password: ${{ inputs.registry_password }}

      - name: Pull image
        shell: bash
        run: docker pull ${{ inputs.acr }}/${{ inputs.module }}:${{ inputs.tag }}

      - name: Run Trivy vulnerability scanner
        uses: aquasecurity/trivy-action@0.28.0
        with:
          image-ref: '${{ inputs.acr }}/${{ inputs.module }}:${{ inputs.tag }}'
          format: 'github'
          output: 'scan-results.sbom.json'
          exit-code: '0'
          ignore-unfixed: true
          vuln-type: 'os,library'
          severity: 'MEDIUM,CRITICAL,HIGH'
          github-pat: '${{ inputs.token }}'

      - name: Upload trivy report as a Github artifact
        uses: actions/upload-artifact@v4
        with:
          name: trivy-sbom-report
          path: '${{ github.workspace }}/scan-results.sbom.json'
          retention-days: 1