name: 'Reusable composite action for Trivy vulnerability scanning'
description: 'Performs vulnerability scanning on container images using Trivy and uploads the results as an artifact.'
inputs:
  image:
    description: 'Container image to scan'
    required: true
    type: string
  severity_threshold:
    description: 'Vulnerability severity threshold (LOW, MEDIUM, HIGH, CRITICAL)'
    required: false
    default: 'MEDIUM,CRITICAL,HIGH'
    type: string
  format:
    description: 'Output format (table, json, template, cyclonedx, spdx-json, spdx-tag-value, github)'
    required: false
    default: 'sarif'
    type: string
  registry_username:
    description: 'ACR registry username'
    required: true
    type: string
  registry_password:
    description: 'ACR registry password'
    required: true
    type: string
  token:
    description: 'GitHub token for authentication'
    required: true
    type: string


runs:
    using: "composite"
    steps:

      - name: 'Checkout GitHub Action'
        uses: actions/checkout@main

      - name: Run Trivy vulnerability scanner
        uses: aquasecurity/trivy-action@0.28.0
        with:
          image-ref: '${{ inputs.image }}'
          scan-type: image
          format: 'sarif'
          output: 'trivy-scan-results.sarif'
          exit-code: '0'
          ignore-unfixed: true
          vuln-type: 'os,library'
          severity: '${{ inputs.severity_threshold }}'
          github-pat: '${{ inputs.token }}'
          timeout: '15m'
        env:
          TRIVY_USERNAME: ${{ inputs.registry_username }}
          TRIVY_PASSWORD: ${{ inputs.registry_password }}

      - name: Upload trivy report as a Github artifact
        uses: actions/upload-artifact@v4
        with:
          name: trivy-report
          path: 'trivy-scan-results.sarif'
          retention-days: 5

      - name: Upload Trivy scan results to GitHub Security tab
        uses: github/codeql-action/upload-sarif@v3
        with:
            sarif_file: 'trivy-scan-results.sarif'